name: Analyse the project with SonarCloud.io


on:
  workflow_call:
    inputs:
      source-path:
        required: true
        type: string
    secrets:
      sonarToken:
        required: true


jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Compile the project
      run: mvn -B --file pom.xml clean compile

    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@v3.1.0
      env:
        SONAR_TOKEN: ${{ secrets.sonarToken }}
      with:
        args:  >
          -Dsonar.projectKey=${{ vars.SONAR_PROJECTKEY }}
          -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          -Dsonar.sources=${{ inputs.source-path }}
        projectBaseDir: .
