name: Analyse the project with SonarCloud

on:
  push:
    branches-ignore: [ "main" ]
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: clear project
        run: mvn clean

      - name: Compile the project
        run: mvn -B --file pom.xml compile

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:  >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECTKEY }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.sources=target/
          projectBaseDir: .
