name: Analyse the project with SonarCloud

on:
  push:
    branches-ignore: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=${{ vars.SONAR_PROJECTKEY }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
          projectBaseDir: .
