name: Validate SpringBoot PR with Maven


on:
  push:
    branches-ignore: [ "main" ]
  # pull_request:
  #   branches:
  #     - "main"


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: clear project
      run: mvn clean

    - name: Compile the project
      run: mvn -B --file pom.xml compile

    - name: Unittest execution
      run: mvn -B --file pom.xml test

    - name: Build jar file with Maven
      run: mvn -B --file pom.xml package

    - name: Id the jar is created
      id: jar-path
      run: echo "JAR_PATH=$(find ./target -name spring-boot-2-hello-world*.jar)" | tee -a "$GITHUB_OUTPUT"

    - name: Artifact version
      id: artifact-version
      run: echo "ARTIFACT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" | tee -a "$GITHUB_OUTPUT"

    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-2-hello-world-${{ steps.artifact-version.outputs.ARTIFACT_VERSION }}
        path: ${{ steps.jar-path.outputs.JAR_PATH }}
        if-no-files-found: error
        retention-days: 1
        overwrite: true

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  analyse:
    uses: ./.github/workflows/analyse.yml
    with:
      source-path: ./target
    secrets:
      sonarToken: ${{ secrets.SONAR_TOKEN }}
