name: Validate SpringBoot PR with Maven


on:
  push:
    branches-ignore: [ "main" ]
  # pull_request:
  #   branches:
  #     - "main"


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: clear project
      run: mvn clean

    - name: Compile the project
      run: mvn -B --file pom.xml compile

    - name: Unittest execution
      run: mvn -B --file pom.xml test

    - name: Build with Maven
      run: mvn -B --file pom.xml package

    - name: List artifacts
      run: find ./target -name "spring-boot-2-hello-world-*-SNAPSHOT.jar"

    # - name: Staging
    #   run: '[ $(find ./target -name "spring-boot-2-hello-world-*-SNAPSHOT.jar") ] && mkdir staging && cp target/*.jar staging'

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  analyse:
    uses: SemtechTasks/spring-boot-hello-world/.github/workflows/analyse.yml@dev
    with:
      source-path: ./target
    secrets:
      sonarToken: ${{ secrets.SONAR_TOKEN }}
