name: Release the artifact jar on GitHub


on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  release:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build and package
      run: mvn -B --file pom.xml versions:set -DremoveSnapshot && mvn -B --file pom.xml clean package

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        build-args: jar_version=${{ steps.artifact-version.outputs.ARTIFACT_VERSION }}
        context: .
        push: true
        tags: greenhorn/spring-boot-hello-world:${{ steps.artifact-version.outputs.ARTIFACT_VERSION }}

  analyse:
    uses: SemtechTasks/spring-boot-hello-world/.github/workflows/analyse.yml@main
    with:
      source-path: ./target
    secrets:
      sonarToken: ${{ secrets.SONAR_TOKEN }}